name: flutter_beacons
description: A beautiful crypto font pack for Flutter by Cryptowatch.
version: 1.1.0
repository: https://github.com/cryptowatch/beacons
homepage: https://cryptowat.ch

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ^3.3.9

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  code_builder: ^4.0.0
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Beacons
      fonts:
        - asset: fonts/beacons.ttf
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
